import jsPDF from 'jspdf';

export interface CarData {
  make: string;
  model: string;
  year: number;
  score?: number;
  price?: string;
  mpg?: string;
  horsepower?: string;
  seatingCapacity?: number;
  safetyRating?: string;
  pros?: string[];
  cons?: string[];
  specifications?: Record<string, string>;
}

export const generateCarPDF = (car: CarData) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Title
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${car.year} ${car.make} ${car.model}`, margin, yPosition);
  yPosition += 15;

  // CAR-RANKINGS branding
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(100, 100, 100);
  pdf.text("Generated by CAR-RANKINGS", margin, yPosition);
  yPosition += 20;

  // Basic Info
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(0, 0, 0);
  pdf.text("Overview", margin, yPosition);
  yPosition += 10;

  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");

  if (car.price) {
    pdf.text(`Starting Price: ${car.price}`, margin, yPosition);
    yPosition += 8;
  }

  if (car.score) {
    pdf.text(`CAR-RANKINGS Score: ${car.score}/10`, margin, yPosition);
    yPosition += 8;
  }

  if (car.mpg) {
    pdf.text(`Fuel Economy: ${car.mpg}`, margin, yPosition);
    yPosition += 8;
  }

  if (car.horsepower) {
    pdf.text(`Horsepower: ${car.horsepower}`, margin, yPosition);
    yPosition += 8;
  }

  if (car.seatingCapacity) {
    pdf.text(`Seating: ${car.seatingCapacity} passengers`, margin, yPosition);
    yPosition += 8;
  }

  if (car.safetyRating) {
    pdf.text(`Safety Rating: ${car.safetyRating}`, margin, yPosition);
    yPosition += 15;
  }

  // Pros and Cons
  if (car.pros && car.pros.length > 0) {
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Pros", margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    car.pros.forEach((pro) => {
      pdf.text(`• ${pro}`, margin + 5, yPosition);
      yPosition += 6;
    });
    yPosition += 10;
  }

  if (car.cons && car.cons.length > 0) {
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Cons", margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    car.cons.forEach((con) => {
      pdf.text(`• ${con}`, margin + 5, yPosition);
      yPosition += 6;
    });
    yPosition += 15;
  }

  // Specifications
  if (car.specifications) {
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Specifications", margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    Object.entries(car.specifications).forEach(([key, value]) => {
      pdf.text(`${key}: ${value}`, margin, yPosition);
      yPosition += 6;
    });
  }

  // Footer
  const footerY = pdf.internal.pageSize.getHeight() - 20;
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text("For the latest rankings and comparisons, visit car-rankings.com", margin, footerY);

  // Download the PDF
  const fileName = `${car.year}-${car.make}-${car.model}-specs.pdf`.replace(/\s+/g, '-').toLowerCase();
  pdf.save(fileName);
};

export const generateComparisonPDF = (cars: CarData[], title = "Car Comparison") => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Title
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.text(title, margin, yPosition);
  yPosition += 15;

  // Branding
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(100, 100, 100);
  pdf.text("Generated by CAR-RANKINGS", margin, yPosition);
  yPosition += 20;

  // Car comparison table
  cars.forEach((car, index) => {
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(0, 0, 0);
    pdf.text(`${index + 1}. ${car.year} ${car.make} ${car.model}`, margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    
    if (car.price) {
      pdf.text(`Price: ${car.price}`, margin + 10, yPosition);
      yPosition += 6;
    }
    
    if (car.score) {
      pdf.text(`Score: ${car.score}/10`, margin + 10, yPosition);
      yPosition += 6;
    }
    
    if (car.mpg) {
      pdf.text(`MPG: ${car.mpg}`, margin + 10, yPosition);
      yPosition += 6;
    }
    
    yPosition += 10;
  });

  // Footer
  const footerY = pdf.internal.pageSize.getHeight() - 20;
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text("For detailed analysis, visit car-rankings.com", margin, footerY);

  const fileName = `car-comparison-${Date.now()}.pdf`;
  pdf.save(fileName);
};